-- Add username field to profiles table
ALTER TABLE profiles ADD COLUMN username TEXT UNIQUE;

-- Create index for username for faster lookups
CREATE INDEX IF NOT EXISTS idx_profiles_username ON profiles(username);

-- Create function to generate username from full_name if not provided
CREATE OR REPLACE FUNCTION generate_username(full_name TEXT)
RETURNS TEXT AS $$
BEGIN
  -- Remove special characters and convert to lowercase
  RETURN lower(regexp_replace(full_name, '[^a-zA-Z0-9\s]', '', 'g'));
END;
$$ LANGUAGE plpgsql;

-- Update existing profiles to have usernames (you might need to run this manually)
-- UPDATE profiles SET username = generate_username(full_name) WHERE username IS NULL;

-- Create portfolio analytics table for tracking views
CREATE TABLE IF NOT EXISTS portfolio_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL REFERENCES profiles(username) ON DELETE CASCADE,
  view_count INTEGER DEFAULT 1,
  last_viewed_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for analytics
CREATE INDEX IF NOT EXISTS idx_portfolio_analytics_username ON portfolio_analytics(username);

-- Function to increment portfolio view count
CREATE OR REPLACE FUNCTION increment_portfolio_view(portfolio_username TEXT)
RETURNS VOID AS $$
BEGIN
  INSERT INTO portfolio_analytics (username, view_count, last_viewed_at)
  VALUES (portfolio_username, 1, NOW())
  ON CONFLICT (username) 
  DO UPDATE SET 
    view_count = portfolio_analytics.view_count + 1,
    last_viewed_at = NOW();
END;
$$ LANGUAGE plpgsql;
