-- Enhanced portfolio analytics schema

-- Add detailed analytics tracking
ALTER TABLE portfolio_analytics ADD COLUMN IF NOT EXISTS session_id TEXT;
ALTER TABLE portfolio_analytics ADD COLUMN IF NOT EXISTS ip_address TEXT;
ALTER TABLE portfolio_analytics ADD COLUMN IF NOT EXISTS user_agent TEXT;
ALTER TABLE portfolio_analytics ADD COLUMN IF NOT EXISTS referrer TEXT;
ALTER TABLE portfolio_analytics ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE portfolio_analytics ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE portfolio_analytics ADD COLUMN IF NOT EXISTS time_spent_seconds INTEGER DEFAULT 0;
ALTER TABLE portfolio_analytics ADD COLUMN IF NOT EXISTS pages_viewed INTEGER DEFAULT 1;
ALTER TABLE portfolio_analytics ADD COLUMN IF NOT EXISTS bounce_rate BOOLEAN DEFAULT TRUE;

-- Create project-specific analytics table
CREATE TABLE IF NOT EXISTS project_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  username TEXT REFERENCES profiles(username) ON DELETE CASCADE,
  session_id TEXT,
  view_duration_seconds INTEGER DEFAULT 0,
  clicked_github BOOLEAN DEFAULT FALSE,
  clicked_demo BOOLEAN DEFAULT FALSE,
  viewed_at TIMESTAMPTZ DEFAULT NOW(),
  ip_address TEXT,
  user_agent TEXT
);

-- Create visitor sessions table
CREATE TABLE IF NOT EXISTS visitor_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT UNIQUE NOT NULL,
  username TEXT REFERENCES profiles(username) ON DELETE CASCADE,
  started_at TIMESTAMPTZ DEFAULT NOW(),
  ended_at TIMESTAMPTZ,
  total_duration_seconds INTEGER DEFAULT 0,
  pages_viewed INTEGER DEFAULT 0,
  projects_viewed TEXT[] DEFAULT '{}',
  referrer TEXT,
  ip_address TEXT,
  user_agent TEXT,
  country TEXT,
  city TEXT,
  is_returning_visitor BOOLEAN DEFAULT FALSE
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_portfolio_analytics_session_id ON portfolio_analytics(session_id);
CREATE INDEX IF NOT EXISTS idx_portfolio_analytics_created_at ON portfolio_analytics(created_at);
CREATE INDEX IF NOT EXISTS idx_project_analytics_project_id ON project_analytics(project_id);
CREATE INDEX IF NOT EXISTS idx_project_analytics_viewed_at ON project_analytics(viewed_at);
CREATE INDEX IF NOT EXISTS idx_visitor_sessions_username ON visitor_sessions(username);
CREATE INDEX IF NOT EXISTS idx_visitor_sessions_started_at ON visitor_sessions(started_at);

-- Function to get portfolio analytics overview
CREATE OR REPLACE FUNCTION get_portfolio_analytics_overview(portfolio_username TEXT)
RETURNS TABLE(
  total_views BIGINT,
  unique_visitors BIGINT,
  returning_visitors BIGINT,
  avg_session_duration DECIMAL,
  bounce_rate DECIMAL,
  total_projects_viewed BIGINT,
  most_viewed_project TEXT,
  views_today BIGINT,
  views_this_week BIGINT,
  views_this_month BIGINT
) AS $$
BEGIN
  RETURN QUERY
  WITH 
  daily_views AS (
    SELECT COUNT(*) as count
    FROM portfolio_analytics 
    WHERE username = portfolio_username 
    AND DATE(created_at) = CURRENT_DATE
  ),
  weekly_views AS (
    SELECT COUNT(*) as count
    FROM portfolio_analytics 
    WHERE username = portfolio_username 
    AND created_at >= DATE_TRUNC('week', CURRENT_DATE)
  ),
  monthly_views AS (
    SELECT COUNT(*) as count
    FROM portfolio_analytics 
    WHERE username = portfolio_username 
    AND created_at >= DATE_TRUNC('month', CURRENT_DATE)
  ),
  project_stats AS (
    SELECT 
      p.project_name,
      COUNT(*) as view_count
    FROM project_analytics pa
    JOIN projects p ON pa.project_id = p.id
    WHERE pa.username = portfolio_username
    GROUP BY p.project_name
    ORDER BY view_count DESC
    LIMIT 1
  )
  SELECT 
    (SELECT COUNT(*) FROM portfolio_analytics WHERE username = portfolio_username),
    (SELECT COUNT(DISTINCT session_id) FROM portfolio_analytics WHERE username = portfolio_username),
    (SELECT COUNT(*) FROM visitor_sessions WHERE username = portfolio_username AND is_returning_visitor = TRUE),
    COALESCE((SELECT AVG(total_duration_seconds) FROM visitor_sessions WHERE username = portfolio_username), 0),
    CASE 
      WHEN (SELECT COUNT(*) FROM visitor_sessions WHERE username = portfolio_username) > 0
      THEN (SELECT SUM(CASE WHEN pages_viewed = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) FROM visitor_sessions WHERE username = portfolio_username)
      ELSE 0
    END,
    (SELECT SUM(pages_viewed) FROM visitor_sessions WHERE username = portfolio_username),
    (SELECT project_name FROM project_stats LIMIT 1),
    (SELECT count FROM daily_views),
    (SELECT count FROM weekly_views),
    (SELECT count FROM monthly_views);
END;
$$ LANGUAGE plpgsql;

-- Function to get project analytics
CREATE OR REPLACE FUNCTION get_project_analytics(portfolio_username TEXT)
RETURNS TABLE(
  project_id BIGINT,
  project_name TEXT,
  total_views BIGINT,
  unique_views BIGINT,
  github_clicks BIGINT,
  demo_clicks BIGINT,
  avg_view_duration DECIMAL,
  last_viewed TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    p.id,
    p.project_name,
    COUNT(*) as total_views,
    COUNT(DISTINCT pa.session_id) as unique_views,
    SUM(CASE WHEN pa.clicked_github THEN 1 ELSE 0 END) as github_clicks,
    SUM(CASE WHEN pa.clicked_demo THEN 1 ELSE 0 END) as demo_clicks,
    COALESCE(AVG(pa.view_duration_seconds), 0) as avg_view_duration,
    MAX(pa.viewed_at) as last_viewed
  FROM projects p
  LEFT JOIN project_analytics pa ON p.id = pa.project_id
  WHERE p.user_id = (SELECT user_id FROM profiles WHERE username = portfolio_username LIMIT 1)
  GROUP BY p.id, p.project_name
  ORDER BY total_views DESC;
END;
$$ LANGUAGE plpgsql;

-- Function to get visitor timeline data
CREATE OR REPLACE FUNCTION get_visitor_timeline(portfolio_username TEXT, days INTEGER DEFAULT 30)
RETURNS TABLE(
  date DATE,
  views BIGINT,
  unique_visitors BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    DATE(pa.created_at) as date,
    COUNT(*) as views,
    COUNT(DISTINCT pa.session_id) as unique_visitors
  FROM portfolio_analytics pa
  WHERE pa.username = portfolio_username 
    AND pa.created_at >= CURRENT_DATE - INTERVAL '1 day' * days
  GROUP BY DATE(pa.created_at)
  ORDER BY date;
END;
$$ LANGUAGE plpgsql;

-- Function to track portfolio view with enhanced data
CREATE OR REPLACE FUNCTION track_portfolio_view(
  portfolio_username TEXT,
  session_id TEXT,
  ip_address TEXT DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  referrer TEXT DEFAULT NULL,
  country TEXT DEFAULT NULL,
  city TEXT DEFAULT NULL
) RETURNS VOID AS $$
BEGIN
  -- Check if this is a returning visitor
  INSERT INTO visitor_sessions (
    session_id, username, ip_address, user_agent, referrer, country, city, is_returning_visitor
  ) VALUES (
    session_id, portfolio_username, ip_address, user_agent, referrer, country, city,
    EXISTS(SELECT 1 FROM visitor_sessions WHERE username = portfolio_username AND ip_address = ip_address LIMIT 1)
  )
  ON CONFLICT (session_id) DO NOTHING;
  
  -- Increment portfolio view count
  INSERT INTO portfolio_analytics (
    username, session_id, ip_address, user_agent, referrer, country, city
  ) VALUES (
    portfolio_username, session_id, ip_address, user_agent, referrer, country, city
  );
END;
$$ LANGUAGE plpgsql;
