-- AI Features Database Schema

-- AI Resume Templates
CREATE TABLE IF NOT EXISTS ai_resume_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('ats_friendly', 'creative', 'executive', 'technical', 'academic')),
  template_structure JSONB NOT NULL DEFAULT '{}'::jsonb,
  sections JSONB NOT NULL DEFAULT '["header", "summary", "experience", "projects", "skills", "education"]'::jsonb,
  styling JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_premium BOOLEAN DEFAULT FALSE,
  usage_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- User Resume Generations
CREATE TABLE IF NOT EXISTS user_resume_generations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  template_id BIGINT REFERENCES ai_resume_templates(id) ON DELETE SET NULL,
  resume_content JSONB NOT NULL DEFAULT '{}'::jsonb,
  ai_optimizations JSONB DEFAULT '{}'::jsonb,
  target_job_title TEXT,
  target_industry TEXT,
  keywords TEXT[],
  ats_score DECIMAL(3,2) DEFAULT 0.00,
  export_format TEXT DEFAULT 'pdf' CHECK (export_format IN ('pdf', 'docx', 'txt')),
  is_public BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- AI Interview Sessions
CREATE TABLE IF NOT EXISTS ai_interview_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  session_type TEXT NOT NULL CHECK (session_type IN ('technical', 'behavioral', 'mixed', 'case_study')),
  difficulty_level TEXT NOT NULL CHECK (difficulty_level IN ('junior', 'mid', 'senior', 'lead')),
  target_role TEXT,
  industry_focus TEXT,
  questions JSONB NOT NULL DEFAULT '[]'::jsonb,
  responses JSONB DEFAULT '[]'::jsonb,
  ai_feedback JSONB DEFAULT '{}'::jsonb,
  overall_score DECIMAL(3,2) DEFAULT 0.00,
  completed_at TIMESTAMPTZ,
  duration_minutes INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Interview Question Bank
CREATE TABLE IF NOT EXISTS ai_interview_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('technical', 'behavioral', 'situational', 'case_study')),
  difficulty TEXT NOT NULL CHECK (difficulty IN ('junior', 'mid', 'senior', 'lead')),
  role_types TEXT[] DEFAULT '{}',
  industries TEXT[] DEFAULT '{}',
  skills_required TEXT[] DEFAULT '{}',
  ideal_answer_keywords TEXT[] DEFAULT '{}',
  scoring_criteria JSONB DEFAULT '{}'::jsonb,
  usage_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- AI Career Insights
CREATE TABLE IF NOT EXISTS ai_career_insights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  insight_type TEXT NOT NULL CHECK (insight_type IN ('skill_gap', 'career_path', 'salary_insights', 'market_trends', 'networking')),
  insight_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  confidence_score DECIMAL(3,2) DEFAULT 0.00,
  action_items JSONB DEFAULT '[]'::jsonb,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- AI Skill Gap Analysis
CREATE TABLE IF NOT EXISTS ai_skill_gap_analyses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  target_role TEXT NOT NULL,
  current_skills TEXT[] DEFAULT '{}',
  required_skills TEXT[] DEFAULT '{}',
  missing_skills TEXT[] DEFAULT '{}',
  skill_levels JSONB DEFAULT '{}'::jsonb,
  learning_resources JSONB DEFAULT '[]'::jsonb,
  estimated_timeline_months INTEGER,
  priority_level TEXT CHECK (priority_level IN ('low', 'medium', 'high', 'critical')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- AI Portfolio Enhancements
CREATE TABLE IF NOT EXISTS ai_portfolio_enhancements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  enhancement_type TEXT NOT NULL CHECK (enhancement_type IN ('description', 'keywords', 'structure', 'visuals', 'impact')),
  original_content TEXT,
  suggested_content TEXT,
  ai_reasoning TEXT,
  improvement_score DECIMAL(3,2) DEFAULT 0.00,
  is_applied BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_ai_resume_templates_category ON ai_resume_templates(category);
CREATE INDEX IF NOT EXISTS idx_user_resume_generations_user_id ON user_resume_generations(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_interview_sessions_user_id ON ai_interview_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_interview_questions_category ON ai_interview_questions(category);
CREATE INDEX IF NOT EXISTS idx_ai_career_insights_user_id ON ai_career_insights(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_skill_gap_analyses_user_id ON ai_skill_gap_analyses(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_portfolio_enhancements_user_id ON ai_portfolio_enhancements(user_id);

-- Insert default AI resume templates
INSERT INTO ai_resume_templates (name, description, category, template_structure, sections, styling) VALUES
(
  'Modern ATS-Friendly',
  'Clean, professional resume optimized for Applicant Tracking Systems with standard formatting and keyword optimization',
  'ats_friendly',
  '{"layout": "single_column", "font_size": "11pt", "margins": "0.5in", "line_spacing": "1.15"}'::jsonb,
  '["header", "summary", "experience", "projects", "skills", "education", "certifications"]'::jsonb,
  '{"colors": {"primary": "#000000", "accent": "#1a1a1a"}, "fonts": {"body": "Calibri", "headings": "Arial"}}'::jsonb
),
(
  'Creative Designer',
  'Visually appealing resume with modern design elements perfect for creative professionals',
  'creative',
  '{"layout": "two_column", "font_size": "10pt", "margins": "0.75in", "line_spacing": "1.2"}'::jsonb,
  '["header", "summary", "skills", "experience", "projects", "education", "portfolio"]'::jsonb,
  '{"colors": {"primary": "#2c3e50", "accent": "#3498db"}, "fonts": {"body": "Helvetica", "headings": "Montserrat"}}'::jsonb
),
(
  'Technical Executive',
  'Comprehensive resume format for senior technical roles with emphasis on leadership and impact',
  'executive',
  '{"layout": "single_column", "font_size": "11pt", "margins": "0.75in", "line_spacing": "1.15"}'::jsonb,
  '["header", "executive_summary", "leadership_experience", "technical_experience", "projects", "education", "certifications", "awards"]'::jsonb,
  '{"colors": {"primary": "#1f2937", "accent": "#3b82f6"}, "fonts": {"body": "Georgia", "headings": "Times New Roman"}}'::jsonb
),
(
  'Software Engineer',
  'Technical resume optimized for developer roles with emphasis on projects and technical skills',
  'technical',
  '{"layout": "two_column", "font_size": "10pt", "margins": "0.5in", "line_spacing": "1.1"}'::jsonb,
  '["header", "technical_summary", "skills", "experience", "projects", "education", "github", "certifications"]'::jsonb,
  '{"colors": {"primary": "#0f172a", "accent": "#10b981"}, "fonts": {"body": "Consolas", "headings": "Inter"}}'::jsonb
),
(
  'Academic Researcher',
  'CV format optimized for academic and research positions with emphasis on publications and research',
  'academic',
  '{"layout": "single_column", "font_size": "11pt", "margins": "1in", "line_spacing": "1.5"}'::jsonb,
  '["header", "research_interests", "education", "publications", "research_experience", "teaching_experience", "skills", "references"]'::jsonb,
  '{"colors": {"primary": "#1a1a1a", "accent": "#4a5568"}, "fonts": {"body": "Times New Roman", "headings": "Garamond"}}'::jsonb
);

-- Insert sample interview questions
INSERT INTO ai_interview_questions (question, category, difficulty, role_types, industries, skills_required, ideal_answer_keywords, scoring_criteria) VALUES
(
  'Tell me about a challenging project you worked on recently. What was your specific role and how did you overcome obstacles?',
  'behavioral',
  'mid',
  '{"developer", "designer", "manager"}',
  '{"technology", "healthcare", "finance"}',
  '{"problem_solving", "communication", "leadership"}',
  '{"challenging", "overcome", "collaborate", "solution", "impact"}',
  '{"problem_clarity": 0.3, "role_definition": 0.2, "solution_quality": 0.3, "communication": 0.2}'::jsonb
),
(
  'How would you optimize this React component for performance? [Component provided]',
  'technical',
  'senior',
  '{"frontend_developer", "full_stack"}',
  '{"technology", "ecommerce", "saas"}',
  '{"react", "performance", "optimization", "javascript"}',
  '{"memoization", "usememo", "usecallback", "lazy_loading", "code_splitting"}',
  '{"technical_accuracy": 0.4, "performance_impact": 0.3, "code_quality": 0.3}'::jsonb
),
(
  'Design a system architecture for a social media application that needs to handle 1 million daily active users.',
  'case_study',
  'lead',
  '{"software_architect", "backend_developer", "devops"}',
  '{"technology", "social_media", "gaming"}',
  '{"scalability", "microservices", "database", "caching", "load_balancing"}',
  '{"scalability", "microservices", "caching", "database_sharding", "cdn", "load_balancer"}',
  '{"scalability": 0.3, "reliability": 0.2, "cost_efficiency": 0.2, "technical_depth": 0.3}'::jsonb
);

-- Function to generate AI resume content
CREATE OR REPLACE FUNCTION generate_ai_resume_content(
  user_profile_data JSONB,
  template_id BIGINT,
  target_job_title TEXT DEFAULT NULL,
  keywords TEXT[] DEFAULT NULL
) RETURNS TABLE(
  section_name TEXT,
  section_content JSONB,
  ai_suggestions TEXT[]
) AS $$
BEGIN
  -- This function will be implemented with AI integration
  -- For now, return placeholder data
  RETURN QUERY
  SELECT 
    'header'::TEXT,
    jsonb_build_object('name', COALESCE((user_profile_data->>'full_name'), 'John Doe')) as section_content,
    ARRAY['Consider adding a professional headline', 'Include LinkedIn profile URL'] as ai_suggestions
  UNION ALL
  SELECT 
    'summary'::TEXT,
    jsonb_build_object('content', 'Experienced professional with a proven track record...') as section_content,
    ARRAY['Highlight key achievements', 'Quantify your impact'] as ai_suggestions;
END;
$$ LANGUAGE plpgsql;

-- Function to analyze skill gaps
CREATE OR REPLACE FUNCTION analyze_skill_gaps(
  user_skills TEXT[],
  target_role TEXT
) RETURNS TABLE(
  missing_skills TEXT[],
  skill_level_recommendations JSONB,
  learning_resources JSONB
) AS $$
BEGIN
  -- This function will be implemented with AI integration
  -- For now, return placeholder data
  RETURN QUERY
  SELECT 
    ARRAY['Advanced React', 'System Design', 'Team Leadership'] as missing_skills,
    jsonb_build_object('react', 'intermediate', 'design', 'beginner') as skill_level_recommendations,
    jsonb_build_array(
      jsonb_build_object('skill', 'Advanced React', 'resource', 'React Advanced Patterns Course', 'type', 'online_course'),
      jsonb_build_object('skill', 'System Design', 'resource', 'Grokking System Design', 'type', 'book')
    ) as learning_resources;
END;
$$ LANGUAGE plpgsql;
