-- Portfolio Export Functionality Database Schema

-- Export Templates
CREATE TABLE IF NOT EXISTS export_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  export_type TEXT NOT NULL CHECK (export_type IN ('pdf', 'website', 'resume')),
  category TEXT NOT NULL CHECK (category IN ('professional', 'creative', 'technical', 'academic', 'minimal')),
  template_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  styling JSONB NOT NULL DEFAULT '{}'::jsonb,
  preview_image TEXT,
  is_premium BOOLEAN DEFAULT FALSE,
  usage_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Export History
CREATE TABLE IF NOT EXISTS export_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  export_type TEXT NOT NULL CHECK (export_type IN ('pdf', 'website', 'resume')),
  template_id BIGINT REFERENCES export_templates(id) ON DELETE SET NULL,
  export_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  file_path TEXT,
  file_size BIGINT,
  download_count INTEGER DEFAULT 0,
  is_public BOOLEAN DEFAULT FALSE,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Export Settings
CREATE TABLE IF NOT EXISTS export_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  default_pdf_template BIGINT REFERENCES export_templates(id),
  default_website_template BIGINT REFERENCES export_templates(id),
  include_analytics BOOLEAN DEFAULT TRUE,
  watermark_text TEXT,
  custom_branding JSONB DEFAULT '{}'::jsonb,
  privacy_settings JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_export_templates_type ON export_templates(export_type);
CREATE INDEX IF NOT EXISTS idx_export_templates_category ON export_templates(category);
CREATE INDEX IF NOT EXISTS idx_export_history_user_id ON export_history(user_id);
CREATE INDEX IF NOT EXISTS idx_export_history_created_at ON export_history(created_at);
CREATE INDEX IF NOT EXISTS idx_export_settings_user_id ON export_settings(user_id);

-- Insert default export templates
INSERT INTO export_templates (name, description, export_type, category, template_config, styling) VALUES
(
  'Professional Portfolio PDF',
  'Clean, professional PDF layout perfect for job applications and corporate sharing',
  'pdf',
  'professional',
  '{"page_size": "A4", "orientation": "portrait", "margins": {"top": "20mm", "bottom": "20mm", "left": "15mm", "right": "15mm"}, "font_size": "12pt", "line_height": 1.5}'::jsonb,
  '{"colors": {"primary": "#1a1a1a", "accent": "#2563eb", "background": "#ffffff"}, "fonts": {"body": "Inter", "headings": "Inter SemiBold"}}'::jsonb
),
(
  'Creative Designer PDF',
  'Visually appealing PDF with modern design elements for creative professionals',
  'pdf',
  'creative',
  '{"page_size": "A4", "orientation": "portrait", "margins": {"top": "15mm", "bottom": "15mm", "left": "20mm", "right": "20mm"}, "font_size": "11pt", "line_height": 1.4}'::jsonb,
  '{"colors": {"primary": "#7c3aed", "accent": "#ec4899", "background": "#fefefe"}, "fonts": {"body": "Figtree", "headings": "Clash Display"}}'::jsonb
),
(
  'Technical Developer PDF',
  'Code-focused PDF layout optimized for technical portfolios and developer roles',
  'pdf',
  'technical',
  '{"page_size": "A4", "orientation": "portrait", "margins": {"top": "15mm", "bottom": "15mm", "left": "12mm", "right": "12mm"}, "font_size": "10pt", "line_height": 1.3}'::jsonb,
  '{"colors": {"primary": "#0f172a", "accent": "#10b981", "background": "#f8fafc"}, "fonts": {"body": "JetBrains Mono", "headings": "Space Mono"}}'::jsonb
),
(
  'Minimal Modern PDF',
  'Clean, minimalist PDF layout with elegant typography and ample white space',
  'pdf',
  'minimal',
  '{"page_size": "A4", "orientation": "portrait", "margins": {"top": "25mm", "bottom": "25mm", "left": "25mm", "right": "25mm"}, "font_size": "12pt", "line_height": 1.6}'::jsonb,
  '{"colors": {"primary": "#000000", "accent": "#6b7280", "background": "#ffffff"}, "fonts": {"body": "SF Pro Display", "headings": "SF Pro Display"}}'::jsonb
),
(
  'Static Website Export',
  'Generate a complete static website with responsive design and SEO optimization',
  'website',
  'professional',
  '{"framework": "vanilla", "responsive": true, "seo_optimized": true, "minify_assets": true, "progressive_web_app": true}'::jsonb,
  '{"colors": {"primary": "#1f2937", "accent": "#3b82f6", "background": "#ffffff"}, "fonts": {"body": "Inter", "headings": "Inter"}}'::jsonb
);

-- Function to increment export template usage
CREATE OR REPLACE FUNCTION increment_export_template_usage(template_id BIGINT)
RETURNS VOID AS $$
BEGIN
  UPDATE export_templates 
  SET usage_count = usage_count + 1, updated_at = NOW()
  WHERE id = template_id;
END;
$$ LANGUAGE plpgsql;

-- Function to get user export statistics
CREATE OR REPLACE FUNCTION get_user_export_stats(user_uuid UUID)
RETURNS TABLE(
  total_exports BIGINT,
  pdf_exports BIGINT,
  website_exports BIGINT,
  resume_exports BIGINT,
  total_downloads BIGINT,
  most_used_template TEXT,
  last_export_date TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  WITH 
  export_counts AS (
    SELECT 
      COUNT(*) as total,
      COUNT(*) FILTER (WHERE export_type = 'pdf') as pdf_count,
      COUNT(*) FILTER (WHERE export_type = 'website') as website_count,
      COUNT(*) FILTER (WHERE export_type = 'resume') as resume_count,
      SUM(download_count) as downloads,
      MAX(created_at) as last_date
    FROM export_history 
    WHERE user_id = user_uuid
  ),
  template_usage AS (
    SELECT 
      et.name,
      COUNT(*) as usage_count
    FROM export_history eh
    JOIN export_templates et ON eh.template_id = et.id
    WHERE eh.user_id = user_uuid
    GROUP BY et.id, et.name
    ORDER BY usage_count DESC
    LIMIT 1
  )
  SELECT 
    ec.total,
    ec.pdf_count,
    ec.website_count,
    ec.resume_count,
    COALESCE(ec.downloads, 0),
    COALESCE(tu.name, 'No template used'),
    ec.last_date
  FROM export_counts ec
  LEFT JOIN template_usage tu ON true;
END;
$$ LANGUAGE plpgsql;

-- Function to cleanup expired exports
CREATE OR REPLACE FUNCTION cleanup_expired_exports()
RETURNS INTEGER AS $$
DECLARE
  deleted_count INTEGER;
BEGIN
  DELETE FROM export_history 
  WHERE expires_at IS NOT NULL 
    AND expires_at < NOW();
  
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  
  RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;
