-- Add Website Export Templates and Enhance Export System

-- Add more website export templates
INSERT INTO export_templates (name, description, export_type, category, template_config, styling) VALUES
(
  'Professional Portfolio Website',
  'Clean, corporate-style website perfect for job applications and professional networking',
  'website',
  'professional',
  '{"layout": "single_page", "sections": ["hero", "about", "skills", "projects", "contact"], "navigation": true, "footer": true, "animations": "subtle"}'::jsonb,
  '{"colors": {"primary": "#1f2937", "accent": "#3b82f6", "background": "#ffffff", "text": "#111827"}, "fonts": {"body": "Inter", "headings": "Inter SemiBold"}, "spacing": {"section": "80px", "component": "24px"}}'::jsonb
),
(
  'Creative Portfolio Website',
  'Visually stunning website with modern animations and creative layouts',
  'website',
  'creative',
  '{"layout": "multi_page", "sections": ["hero", "about", "gallery", "projects", "testimonials", "contact"], "navigation": true, "footer": true, "animations": "advanced"}'::jsonb,
  '{"colors": {"primary": "#7c3aed", "accent": "#ec4899", "background": "#fefefe", "text": "#1f2937"}, "fonts": {"body": "Figtree", "headings": "Clash Display"}, "spacing": {"section": "100px", "component": "32px"}}'::jsonb
),
(
  'Technical Developer Website',
  'Code-focused website with syntax highlighting and technical project showcases',
  'website',
  'technical',
  '{"layout": "single_page", "sections": ["hero", "about", "skills", "projects", "github", "contact"], "navigation": true, "footer": true, "animations": "minimal", "code_highlighting": true}'::jsonb,
  '{"colors": {"primary": "#0f172a", "accent": "#10b981", "background": "#f8fafc", "text": "#1e293b"}, "fonts": {"body": "JetBrains Mono", "headings": "Space Mono"}, "spacing": {"section": "60px", "component": "20px"}}'::jsonb
),
(
  'Minimal Modern Website',
  'Clean, minimalist website with elegant typography and ample white space',
  'website',
  'minimal',
  '{"layout": "single_page", "sections": ["hero", "about", "projects", "contact"], "navigation": false, "footer": true, "animations": "none"}'::jsonb,
  '{"colors": {"primary": "#000000", "accent": "#6b7280", "background": "#ffffff", "text": "#111827"}, "fonts": {"body": "SF Pro Display", "headings": "SF Pro Display"}, "spacing": {"section": "120px", "component": "40px"}}'::jsonb
),
(
  'Academic Portfolio Website',
  'Research-focused website with publications, education, and academic achievements',
  'website',
  'academic',
  '{"layout": "multi_page", "sections": ["hero", "research", "publications", "education", "teaching", "contact"], "navigation": true, "footer": true, "animations": "professional"}'::jsonb,
  '{"colors": {"primary": "#1a1a1a", "accent": "#4a5568", "background": "#ffffff", "text": "#2d3748"}, "fonts": {"body": "Georgia", "headings": "Garamond"}, "spacing": {"section": "90px", "component": "28px"}}'::jsonb
);

-- Create website export assets table
CREATE TABLE IF NOT EXISTS website_export_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  export_id BIGINT REFERENCES export_history(id) ON DELETE CASCADE,
  asset_type TEXT NOT NULL CHECK (asset_type IN ('css', 'js', 'image', 'font', 'icon')),
  file_path TEXT NOT NULL,
  file_name TEXT NOT NULL,
  file_size BIGINT,
  mime_type TEXT,
  optimized_path TEXT,
  is_compressed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create website export configurations table
CREATE TABLE IF NOT EXISTS website_export_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  template_id BIGINT REFERENCES export_templates(id) ON DELETE SET NULL,
  config_name TEXT NOT NULL,
  seo_settings JSONB DEFAULT '{}'::jsonb,
  analytics_settings JSONB DEFAULT '{}'::jsonb,
  performance_settings JSONB DEFAULT '{}'::jsonb,
  custom_css TEXT,
  custom_js TEXT,
  is_default BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_website_export_assets_export_id ON website_export_assets(export_id);
CREATE INDEX IF NOT EXISTS idx_website_export_assets_type ON website_export_assets(asset_type);
CREATE INDEX IF NOT EXISTS idx_website_export_configs_user_id ON website_export_configs(user_id);
CREATE INDEX IF NOT EXISTS idx_website_export_configs_template_id ON website_export_configs(template_id);

-- Function to generate website export structure
CREATE OR REPLACE FUNCTION generate_website_structure(
  user_profile_data JSONB,
  projects_data JSONB,
  template_config JSONB,
  export_settings JSONB
) RETURNS TABLE(
  file_path TEXT,
  content TEXT,
  file_type TEXT
) AS $$
BEGIN
  -- This function will generate the complete website structure
  -- For now, return placeholder structure
  RETURN QUERY
  SELECT 
    'index.html'::TEXT,
    '<!DOCTYPE html><html><head><title>Portfolio</title></head><body><h1>Portfolio Website</h1></body></html>'::TEXT,
    'html'::TEXT
  UNION ALL
  SELECT 
    'assets/css/main.css'::TEXT,
    'body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }'::TEXT,
    'css'::TEXT
  UNION ALL
  SELECT 
    'assets/js/main.js'::TEXT,
    'console.log("Portfolio website loaded");'::TEXT,
    'js'::TEXT;
END;
$$ LANGUAGE plpgsql;

-- Function to optimize website assets
CREATE OR REPLACE FUNCTION optimize_website_assets(export_id BIGINT)
RETURNS TABLE(
  asset_id BIGINT,
  original_size BIGINT,
  optimized_size BIGINT,
  compression_ratio DECIMAL
) AS $$
BEGIN
  -- This function will handle asset optimization
  -- For now, return placeholder data
  RETURN QUERY
  SELECT 
    wa.id,
    wa.file_size,
    wa.file_size * 0.7, -- Simulate 30% compression
    0.30::DECIMAL
  FROM website_export_assets wa
  WHERE wa.export_id = export_id;
END;
$$ LANGUAGE plpgsql;

-- Function to generate SEO metadata
CREATE OR REPLACE FUNCTION generate_seo_metadata(
  user_profile_data JSONB,
  export_settings JSONB
) RETURNS JSONB AS $$
BEGIN
  RETURN jsonb_build_object(
    'title', COALESCE(user_profile_data->>'full_name', 'Portfolio') || ' - Professional Portfolio',
    'description', COALESCE(user_profile_data->>'bio', 'Professional portfolio showcasing projects and skills'),
    'keywords', COALESCE(ARRAY_TO_STRING(ARRAY(SELECT jsonb_array_elements_text(user_profile_data->'skills')), ', '), 'portfolio, projects, skills'),
    'author', COALESCE(user_profile_data->>'full_name', 'Portfolio Owner'),
    'og_type', 'website',
    'og_site_name', 'Builder LAB Portfolio',
    'twitter_card', 'summary_large_image'
  );
END;
$$ LANGUAGE plpgsql;
