-- Portfolio Theme System Database Schema

-- Theme Definitions
CREATE TABLE IF NOT EXISTS portfolio_themes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('professional', 'creative', 'minimal', 'dark', 'vibrant', 'custom')),
  author_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  is_public BOOLEAN DEFAULT FALSE,
  is_premium BOOLEAN DEFAULT FALSE,
  price DECIMAL(10,2) DEFAULT 0.00,
  rating DECIMAL(3,2) DEFAULT 0.00,
  review_count INTEGER DEFAULT 0,
  download_count INTEGER DEFAULT 0,
  usage_count INTEGER DEFAULT 0,
  theme_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  preview_image TEXT,
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- User Theme Customizations
CREATE TABLE IF NOT EXISTS user_theme_customizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  theme_id BIGINT REFERENCES portfolio_themes(id) ON DELETE CASCADE,
  custom_name TEXT,
  custom_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_active BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, theme_id)
);

-- Theme Usage History
CREATE TABLE IF NOT EXISTS theme_usage_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  theme_id BIGINT REFERENCES portfolio_themes(id) ON DELETE SET NULL,
  applied_at TIMESTAMPTZ DEFAULT NOW(),
  session_duration INTEGER, -- in minutes
  user_agent TEXT,
  ip_address INET
);

-- Theme Reviews and Ratings
CREATE TABLE IF NOT EXISTS theme_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  theme_id BIGINT REFERENCES portfolio_themes(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  review_text TEXT,
  is_verified_purchase BOOLEAN DEFAULT FALSE,
  helpful_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(theme_id, user_id)
);

-- Theme Marketplace Categories
CREATE TABLE IF NOT EXISTS theme_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  icon TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Theme Tags
CREATE TABLE IF NOT EXISTS theme_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  color TEXT DEFAULT '#6b7280',
  usage_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Theme-Tag Relationships
CREATE TABLE IF NOT EXISTS theme_tag_relations (
  theme_id BIGINT REFERENCES portfolio_themes(id) ON DELETE CASCADE,
  tag_id BIGINT REFERENCES theme_tags(id) ON DELETE CASCADE,
  PRIMARY KEY (theme_id, tag_id)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_portfolio_themes_category ON portfolio_themes(category);
CREATE INDEX IF NOT EXISTS idx_portfolio_themes_author_id ON portfolio_themes(author_id);
CREATE INDEX IF NOT EXISTS idx_portfolio_themes_is_public ON portfolio_themes(is_public);
CREATE INDEX IF NOT EXISTS idx_portfolio_themes_rating ON portfolio_themes(rating DESC);
CREATE INDEX IF NOT EXISTS idx_portfolio_themes_download_count ON portfolio_themes(download_count DESC);
CREATE INDEX IF NOT EXISTS idx_user_theme_customizations_user_id ON user_theme_customizations(user_id);
CREATE INDEX IF NOT EXISTS idx_user_theme_customizations_is_active ON user_theme_customizations(is_active);
CREATE INDEX IF NOT EXISTS idx_theme_usage_history_user_id ON theme_usage_history(user_id);
CREATE INDEX IF NOT EXISTS idx_theme_usage_history_applied_at ON theme_usage_history(applied_at DESC);
CREATE INDEX IF NOT EXISTS idx_theme_reviews_theme_id ON theme_reviews(theme_id);
CREATE INDEX IF NOT EXISTS idx_theme_reviews_rating ON theme_reviews(rating DESC);

-- Insert default theme categories
INSERT INTO theme_categories (name, description, icon, sort_order) VALUES
('professional', 'Clean and professional themes for business portfolios', 'briefcase', 1),
('creative', 'Artistic and expressive themes for creative professionals', 'palette', 2),
('minimal', 'Simple and elegant themes with minimal design', 'minus-circle', 3),
('dark', 'Dark mode themes for modern portfolios', 'moon', 4),
('vibrant', 'Colorful and energetic themes for standout portfolios', 'rainbow', 5),
('custom', 'User-created and customized themes', 'settings', 6);

-- Insert default theme tags
INSERT INTO theme_tags (name, color) VALUES
('modern', '#3b82f6'),
('classic', '#6b7280'),
('minimalist', '#10b981'),
('bold', '#ef4444'),
('elegant', '#8b5cf6'),
('tech', '#f59e0b'),
('artistic', '#ec4899'),
('corporate', '#1f2937'),
('portfolio', '#059669'),
('responsive', '#6366f1');

-- Insert default portfolio themes
INSERT INTO portfolio_themes (name, description, category, theme_config, preview_image, tags) VALUES
(
  'Professional Blue',
  'A clean, professional theme with blue accents perfect for business portfolios',
  'professional',
  '{"colors": {"primary": "#1e40af", "secondary": "#3b82f6", "accent": "#60a5fa", "background": "#ffffff", "text": "#1f2937", "textSecondary": "#6b7280"}, "typography": {"fontFamily": "Inter", "headingFont": "Inter SemiBold", "bodySize": "16px", "headingSize": "2.5rem"}, "layout": {"containerWidth": "1200px", "sectionSpacing": "80px", "cardRadius": "12px", "buttonRadius": "8px"}, "animations": {"duration": "0.3s", "easing": "ease-in-out"}}'::jsonb,
  '/themes/previews/professional-blue.jpg',
  ARRAY['modern', 'professional', 'corporate', 'responsive']
),
(
  'Creative Purple',
  'An artistic theme with purple gradients and creative typography',
  'creative',
  '{"colors": {"primary": "#7c3aed", "secondary": "#a78bfa", "accent": "#c4b5fd", "background": "#faf5ff", "text": "#1f2937", "textSecondary": "#6b7280"}, "typography": {"fontFamily": "Figtree", "headingFont": "Clash Display", "bodySize": "16px", "headingSize": "3rem"}, "layout": {"containerWidth": "1400px", "sectionSpacing": "100px", "cardRadius": "16px", "buttonRadius": "12px"}, "animations": {"duration": "0.4s", "easing": "cubic-bezier(0.4, 0, 0.2, 1)"}}'::jsonb,
  '/themes/previews/creative-purple.jpg',
  ARRAY['modern', 'artistic', 'creative', 'bold']
),
(
  'Minimal Gray',
  'A minimalist theme with subtle grays and clean typography',
  'minimal',
  '{"colors": {"primary": "#374151", "secondary": "#6b7280", "accent": "#9ca3af", "background": "#ffffff", "text": "#111827", "textSecondary": "#4b5563"}, "typography": {"fontFamily": "SF Pro Display", "headingFont": "SF Pro Display", "bodySize": "15px", "headingSize": "2.25rem"}, "layout": {"containerWidth": "1100px", "sectionSpacing": "120px", "cardRadius": "8px", "buttonRadius": "6px"}, "animations": {"duration": "0.2s", "easing": "linear"}}'::jsonb,
  '/themes/previews/minimal-gray.jpg',
  ARRAY['minimalist', 'classic', 'elegant', 'modern']
),
(
  'Dark Mode Pro',
  'A sleek dark theme perfect for developers and tech professionals',
  'dark',
  '{"colors": {"primary": "#10b981", "secondary": "#34d399", "accent": "#6ee7b7", "background": "#111827", "text": "#f9fafb", "textSecondary": "#d1d5db"}, "typography": {"fontFamily": "JetBrains Mono", "headingFont": "Space Mono", "bodySize": "15px", "headingSize": "2.5rem"}, "layout": {"containerWidth": "1300px", "sectionSpacing": "90px", "cardRadius": "12px", "buttonRadius": "8px"}, "animations": {"duration": "0.3s", "easing": "ease-out"}}'::jsonb,
  '/themes/previews/dark-pro.jpg',
  ARRAY['modern', 'tech', 'minimalist', 'responsive']
),
(
  'Vibrant Sunset',
  'A colorful theme with sunset gradients and energetic design',
  'vibrant',
  '{"colors": {"primary": "#f97316", "secondary": "#fb923c", "accent": "#fed7aa", "background": "#fff7ed", "text": "#7c2d12", "textSecondary": "#9a3412"}, "typography": {"fontFamily": "Poppins", "headingFont": "Poppins Bold", "bodySize": "16px", "headingSize": "3rem"}, "layout": {"containerWidth": "1200px", "sectionSpacing": "80px", "cardRadius": "20px", "buttonRadius": "12px"}, "animations": {"duration": "0.5s", "easing": "ease-in-out"}}'::jsonb,
  '/themes/previews/vibrant-sunset.jpg',
  ARRAY['bold', 'artistic', 'creative', 'modern']
);

-- Function to apply theme to user profile
CREATE OR REPLACE FUNCTION apply_theme_to_profile(
  user_uuid UUID,
  theme_id BIGINT,
  custom_config JSONB DEFAULT NULL
) RETURNS BOOLEAN AS $$
DECLARE
  theme_record RECORD;
  existing_customization RECORD;
BEGIN
  -- Get theme details
  SELECT * INTO theme_record FROM portfolio_themes WHERE id = theme_id;
  
  IF NOT FOUND THEN
    RETURN FALSE;
  END IF;
  
  -- Check if user has existing customization
  SELECT * INTO existing_customization 
  FROM user_theme_customizations 
  WHERE user_id = user_uuid AND theme_id = theme_id;
  
  IF existing_customization.id IS NOT NULL THEN
    -- Update existing customization
    UPDATE user_theme_customizations 
    SET 
      custom_config = COALESCE(custom_config, theme_record.theme_config),
      is_active = TRUE,
      updated_at = NOW()
    WHERE user_id = user_uuid AND theme_id = theme_id;
  ELSE
    -- Create new customization
    INSERT INTO user_theme_customizations (user_id, theme_id, custom_config, is_active)
    VALUES (user_uuid, theme_id, COALESCE(custom_config, theme_record.theme_config), TRUE);
  END IF;
  
  -- Deactivate other themes for this user
  UPDATE user_theme_customizations 
  SET is_active = FALSE 
  WHERE user_id = user_uuid AND theme_id != theme_id;
  
  -- Record theme usage
  INSERT INTO theme_usage_history (user_id, theme_id)
  VALUES (user_uuid, theme_id);
  
  -- Update theme usage count
  UPDATE portfolio_themes 
  SET usage_count = usage_count + 1 
  WHERE id = theme_id;
  
  RETURN TRUE;
END;
$$ LANGUAGE plpgsql;

-- Function to get user's active theme
CREATE OR REPLACE FUNCTION get_user_active_theme(user_uuid UUID)
RETURNS TABLE(
  theme_id BIGINT,
  theme_name TEXT,
  theme_category TEXT,
  theme_config JSONB,
  custom_config JSONB,
  applied_at TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    pt.id,
    pt.name,
    pt.category,
    pt.theme_config,
    utc.custom_config,
    utc.updated_at
  FROM user_theme_customizations utc
  JOIN portfolio_themes pt ON utc.theme_id = pt.id
  WHERE utc.user_id = user_uuid AND utc.is_active = TRUE;
END;
$$ LANGUAGE plpgsql;

-- Function to generate theme CSS
CREATE OR REPLACE FUNCTION generate_theme_css(theme_config JSONB)
RETURNS TEXT AS $$
DECLARE
  css_content TEXT := '';
  colors JSONB;
  typography JSONB;
  layout JSONB;
  animations JSONB;
BEGIN
  -- Extract theme components
  colors := COALESCE(theme_config->'colors', '{}'::jsonb);
  typography := COALESCE(theme_config->'typography', '{}'::jsonb);
  layout := COALESCE(theme_config->'layout', '{}'::jsonb);
  animations := COALESCE(theme_config->'animations', '{}'::jsonb);
  
  -- Generate CSS variables
  css_content := css_content || ':root {' || E'\n';
  
  -- Color variables
  css_content := css_content || '  --color-primary: ' || COALESCE(colors->>'primary', '#3b82f6') || ';' || E'\n';
  css_content := css_content || '  --color-secondary: ' || COALESCE(colors->>'secondary', '#6b7280') || ';' || E'\n';
  css_content := css_content || '  --color-accent: ' || COALESCE(colors->>'accent', '#60a5fa') || ';' || E'\n';
  css_content := css_content || '  --color-background: ' || COALESCE(colors->>'background', '#ffffff') || ';' || E'\n';
  css_content := css_content || '  --color-text: ' || COALESCE(colors->>'text', '#1f2937') || ';' || E'\n';
  css_content := css_content || '  --color-text-secondary: ' || COALESCE(colors->>'textSecondary', '#6b7280') || ';' || E'\n';
  
  -- Typography variables
  css_content := css_content || '  --font-family: ' || COALESCE(typography->>'fontFamily', 'Inter') || ';' || E'\n';
  css_content := css_content || '  --font-heading: ' || COALESCE(typography->>'headingFont', 'Inter SemiBold') || ';' || E'\n';
  css_content := css_content || '  --font-size-body: ' || COALESCE(typography->>'bodySize', '16px') || ';' || E'\n';
  css_content := css_content || '  --font-size-heading: ' || COALESCE(typography->>'headingSize', '2.5rem') || ';' || E'\n';
  
  -- Layout variables
  css_content := css_content || '  --container-width: ' || COALESCE(layout->>'containerWidth', '1200px') || ';' || E'\n';
  css_content := css_content || '  --section-spacing: ' || COALESCE(layout->>'sectionSpacing', '80px') || ';' || E'\n';
  css_content := css_content || '  --border-radius-card: ' || COALESCE(layout->>'cardRadius', '12px') || ';' || E'\n';
  css_content := css_content || '  --border-radius-button: ' || COALESCE(layout->>'buttonRadius', '8px') || ';' || E'\n';
  
  -- Animation variables
  css_content := css_content || '  --animation-duration: ' || COALESCE(animations->>'duration', '0.3s') || ';' || E'\n';
  css_content := css_content || '  --animation-easing: ' || COALESCE(animations->>'easing', 'ease-in-out') || ';' || E'\n';
  
  css_content := css_content || '}' || E'\n';
  
  -- Generate utility classes
  css_content := css_content || E'\n';
  css_content := css_content || '/* Theme Utility Classes */' || E'\n';
  css_content := css_content || '.bg-primary { background-color: var(--color-primary); }' || E'\n';
  css_content := css_content || '.bg-secondary { background-color: var(--color-secondary); }' || E'\n';
  css_content := css_content || '.bg-accent { background-color: var(--color-accent); }' || E'\n';
  css_content := css_content || '.text-primary { color: var(--color-primary); }' || E'\n';
  css_content := css_content || '.text-secondary { color: var(--color-secondary); }' || E'\n';
  css_content := css_content || '.text-accent { color: var(--color-accent); }' || E'\n';
  
  css_content := css_content || E'\n';
  css_content := css_content || '/* Typography Classes */' || E'\n';
  css_content := css_content || 'body { font-family: var(--font-family); font-size: var(--font-size-body); color: var(--color-text); }' || E'\n';
  css_content := css_content || 'h1, h2, h3, h4, h5, h6 { font-family: var(--font-heading); color: var(--color-text); }' || E'\n';
  css_content := css_content || 'h1 { font-size: var(--font-size-heading); }' || E'\n';
  
  css_content := css_content || E'\n';
  css_content := css_content || '/* Layout Classes */' || E'\n';
  css_content := css_content || '.container { max-width: var(--container-width); margin: 0 auto; padding: 0 20px; }' || E'\n';
  css_content := css_content || '.card { border-radius: var(--border-radius-card); }' || E'\n';
  css_content := css_content || '.btn { border-radius: var(--border-radius-button); }' || E'\n';
  
  css_content := css_content || E'\n';
  css_content := css_content || '/* Animation Classes */' || E'\n';
  css_content := css_content || '.transition { transition: all var(--animation-duration) var(--animation-easing); }' || E'\n';
  
  RETURN css_content;
END;
$$ LANGUAGE plpgsql;

-- Function to update theme rating
CREATE OR REPLACE FUNCTION update_theme_rating(theme_id BIGINT)
RETURNS VOID AS $$
DECLARE
  avg_rating DECIMAL;
  review_count_val INTEGER;
BEGIN
  SELECT 
    COALESCE(AVG(rating), 0),
    COUNT(*)
  INTO avg_rating, review_count_val
  FROM theme_reviews 
  WHERE theme_id = theme_id;
  
  UPDATE portfolio_themes 
  SET 
    rating = avg_rating,
    review_count = review_count_val,
    updated_at = NOW()
  WHERE id = theme_id;
END;
$$ LANGUAGE plpgsql;

-- Function to get popular themes
CREATE OR REPLACE FUNCTION get_popular_themes(limit_count INTEGER DEFAULT 10)
RETURNS TABLE(
  theme_id BIGINT,
  theme_name TEXT,
  theme_category TEXT,
  rating DECIMAL,
  download_count INTEGER,
  usage_count INTEGER,
  preview_image TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    pt.id,
    pt.name,
    pt.category,
    pt.rating,
    pt.download_count,
    pt.usage_count,
    pt.preview_image
  FROM portfolio_themes pt
  WHERE pt.is_public = TRUE
  ORDER BY 
    (pt.rating * 0.4 + pt.download_count * 0.3 + pt.usage_count * 0.3) DESC,
    pt.created_at DESC
  LIMIT limit_count;
END;
$$ LANGUAGE plpgsql;
