-- Collaboration System Database Schema

-- Team Workspaces
CREATE TABLE IF NOT EXISTS team_workspaces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  is_active BOOLEAN DEFAULT TRUE,
  is_public BOOLEAN DEFAULT FALSE,
  invite_code TEXT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Team Members
CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES team_workspaces(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'editor', 'viewer')),
  status TEXT NOT NULL CHECK (status IN ('active', 'pending', 'inactive')),
  invited_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  invited_at TIMESTAMPTZ DEFAULT NOW(),
  joined_at TIMESTAMPTZ,
  last_active TIMESTAMPTZ,
  UNIQUE(team_id, user_id)
);

-- Shared Projects
CREATE TABLE IF NOT EXISTS shared_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  team_id BIGINT REFERENCES team_workspaces(id) ON DELETE CASCADE,
  shared_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  permission_level TEXT NOT NULL CHECK (permission_level IN ('read', 'write', 'admin')),
  is_featured BOOLEAN DEFAULT FALSE,
  shared_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Collaboration Activities
CREATE TABLE IF NOT EXISTS collaboration_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES team_workspaces(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action_type TEXT NOT NULL CHECK (action_type IN ('project_created', 'project_updated', 'project_shared', 'member_added', 'member_removed', 'role_changed', 'comment_added', 'theme_changed')),
  target_id BIGINT, -- ID of the affected item (project, user, etc.)
  target_type TEXT, -- Type of the affected item ('project', 'user', 'theme', etc.)
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Portfolio Shares
CREATE TABLE IF NOT EXISTS portfolio_shares (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portfolio_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  shared_by UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  share_token TEXT UNIQUE,
  permission_level TEXT NOT NULL CHECK (permission_level IN ('view', 'comment', 'edit')),
  expires_at TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT TRUE,
  view_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Comments and Feedback
CREATE TABLE IF NOT EXISTS portfolio_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portfolio_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  author_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  parent_id BIGINT REFERENCES portfolio_comments(id) ON DELETE CASCADE,
  is_resolved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Collaboration Invitations
CREATE TABLE IF NOT EXISTS collaboration_invitations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES team_workspaces(id) ON DELETE CASCADE,
  invited_email TEXT NOT NULL,
  invited_by UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('admin', 'editor', 'viewer')),
  message TEXT,
  token TEXT UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('pending', 'accepted', 'declined', 'expired')),
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  responded_at TIMESTAMPTZ
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_team_workspaces_owner_id ON team_workspaces(owner_id);
CREATE INDEX IF NOT EXISTS idx_team_workspaces_invite_code ON team_workspaces(invite_code);
CREATE INDEX IF NOT EXISTS idx_team_members_team_id ON team_members(team_id);
CREATE INDEX IF NOT EXISTS idx_team_members_user_id ON team_members(user_id);
CREATE INDEX IF NOT EXISTS idx_team_members_status ON team_members(status);
CREATE INDEX IF NOT EXISTS idx_shared_projects_team_id ON shared_projects(team_id);
CREATE INDEX IF NOT EXISTS idx_shared_projects_project_id ON shared_projects(project_id);
CREATE INDEX IF NOT EXISTS idx_collaboration_activities_team_id ON collaboration_activities(team_id);
CREATE INDEX IF NOT EXISTS idx_collaboration_activities_created_at ON collaboration_activities(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_portfolio_shares_share_token ON portfolio_shares(share_token);
CREATE INDEX IF NOT EXISTS idx_portfolio_shares_portfolio_id ON portfolio_shares(portfolio_id);
CREATE INDEX IF NOT EXISTS idx_portfolio_comments_portfolio_id ON portfolio_comments(portfolio_id);
CREATE INDEX IF NOT EXISTS idx_portfolio_comments_project_id ON portfolio_comments(project_id);
CREATE INDEX IF NOT EXISTS idx_collaboration_invitations_token ON collaboration_invitations(token);
CREATE INDEX IF NOT EXISTS idx_collaboration_invitations_status ON collaboration_invitations(status);

-- Function to generate unique invite code
CREATE OR REPLACE FUNCTION generate_invite_code()
RETURNS TEXT AS $$
DECLARE
  code TEXT;
  attempts INTEGER := 0;
BEGIN
  LOOP
    code := upper(substring(md5(random()::text), 1, 8));
    EXIT WHEN NOT EXISTS (SELECT 1 FROM team_workspaces WHERE invite_code = code);
    attempts := attempts + 1;
    IF attempts > 10 THEN
      RAISE EXCEPTION 'Failed to generate unique invite code after 10 attempts';
    END IF;
  END LOOP;
  RETURN code;
END;
$$ LANGUAGE plpgsql;

-- Function to create team workspace
CREATE OR REPLACE FUNCTION create_team_workspace(
  workspace_name TEXT,
  workspace_description TEXT DEFAULT NULL,
  owner_uuid UUID,
  is_public_workspace BOOLEAN DEFAULT FALSE
) RETURNS BIGINT AS $$
DECLARE
  workspace_id BIGINT;
BEGIN
  -- Create workspace
  INSERT INTO team_workspaces (name, description, owner_id, is_public, invite_code)
  VALUES (workspace_name, workspace_description, owner_uuid, is_public_workspace, generate_invite_code())
  RETURNING id INTO workspace_id;
  
  -- Add owner as team member
  INSERT INTO team_members (team_id, user_id, role, status, joined_at, last_active)
  VALUES (workspace_id, owner_uuid, 'owner', 'active', NOW(), NOW());
  
  -- Log activity
  INSERT INTO collaboration_activities (team_id, user_id, action_type, metadata)
  VALUES (workspace_id, owner_uuid, 'member_added', jsonb_build_object('role', 'owner'));
  
  RETURN workspace_id;
END;
$$ LANGUAGE plpgsql;

-- Function to add team member
CREATE OR REPLACE FUNCTION add_team_member(
  team_id BIGINT,
  user_uuid UUID,
  member_role TEXT DEFAULT 'editor',
  invited_by_uuid UUID DEFAULT NULL
) RETURNS BOOLEAN AS $$
DECLARE
  existing_member RECORD;
BEGIN
  -- Check if user is already a member
  SELECT * INTO existing_member 
  FROM team_members 
  WHERE team_id = team_id AND user_id = user_uuid;
  
  IF existing_member.id IS NOT NULL THEN
    -- Update existing member
    UPDATE team_members 
    SET 
      role = member_role,
      status = 'active',
      joined_at = NOW(),
      last_active = NOW()
    WHERE team_id = team_id AND user_id = user_uuid;
  ELSE
    -- Add new member
    INSERT INTO team_members (team_id, user_id, role, status, invited_by, joined_at, last_active)
    VALUES (team_id, user_uuid, member_role, 'active', invited_by_uuid, NOW(), NOW());
  END IF;
  
  -- Log activity
  INSERT INTO collaboration_activities (team_id, user_id, action_type, metadata)
  VALUES (team_id, invited_by_uuid, 'member_added', jsonb_build_object('role', member_role));
  
  RETURN TRUE;
END;
$$ LANGUAGE plpgsql;

-- Function to share project with team
CREATE OR REPLACE FUNCTION share_project_with_team(
  project_id BIGINT,
  team_id BIGINT,
  shared_by_uuid UUID,
  permission_level TEXT DEFAULT 'read'
) RETURNS BOOLEAN AS $$
DECLARE
  existing_share RECORD;
BEGIN
  -- Check if project is already shared
  SELECT * INTO existing_share 
  FROM shared_projects 
  WHERE project_id = project_id AND team_id = team_id;
  
  IF existing_share.id IS NOT NULL THEN
    -- Update existing share
    UPDATE shared_projects 
    SET 
      permission_level = permission_level,
      shared_by = shared_by_uuid,
      updated_at = NOW()
    WHERE project_id = project_id AND team_id = team_id;
  ELSE
    -- Add new share
    INSERT INTO shared_projects (project_id, team_id, shared_by, permission_level)
    VALUES (project_id, team_id, shared_by_uuid, permission_level);
  END IF;
  
  -- Log activity
  INSERT INTO collaboration_activities (team_id, user_id, action_type, target_id, target_type, metadata)
  VALUES (team_id, shared_by_uuid, 'project_shared', project_id, 'project', 
          jsonb_build_object('permission_level', permission_level));
  
  RETURN TRUE;
END;
$$ LANGUAGE plpgsql;

-- Function to get team activity feed
CREATE OR REPLACE FUNCTION get_team_activity_feed(
  team_id BIGINT,
  limit_count INTEGER DEFAULT 20,
  offset_count INTEGER DEFAULT 0
) RETURNS TABLE(
  id BIGINT,
  action_type TEXT,
  user_name TEXT,
  user_avatar TEXT,
  target_id BIGINT,
  target_type TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    ca.id,
    ca.action_type,
    p.full_name,
    p.avatar_url,
    ca.target_id,
    ca.target_type,
    ca.metadata,
    ca.created_at
  FROM collaboration_activities ca
  LEFT JOIN profiles p ON ca.user_id = p.user_id
  WHERE ca.team_id = team_id
  ORDER BY ca.created_at DESC
  LIMIT limit_count OFFSET offset_count;
END;
$$ LANGUAGE plpgsql;

-- Function to get user's teams
CREATE OR REPLACE FUNCTION get_user_teams(user_uuid UUID)
RETURNS TABLE(
  team_id BIGINT,
  team_name TEXT,
  team_description TEXT,
  user_role TEXT,
  member_count INTEGER,
  is_owner BOOLEAN,
  created_at TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    tw.id,
    tw.name,
    tw.description,
    tm.role,
    (SELECT COUNT(*) FROM team_members WHERE team_id = tw.id AND status = 'active'),
    tm.role = 'owner',
    tw.created_at
  FROM team_workspaces tw
  JOIN team_members tm ON tw.id = tm.team_id
  WHERE tm.user_id = user_uuid AND tm.status = 'active'
  ORDER BY tw.updated_at DESC;
END;
$$ LANGUAGE plpgsql;

-- Function to generate portfolio share token
CREATE OR REPLACE FUNCTION generate_portfolio_share(
  portfolio_uuid UUID,
  shared_by_uuid UUID,
  permission_level TEXT DEFAULT 'view',
  expires_hours INTEGER DEFAULT NULL
) RETURNS TEXT AS $$
DECLARE
  share_token TEXT;
  expires_at TIMESTAMPTZ;
BEGIN
  -- Generate unique token
  share_token := encode(sha256(random()::text || portfolio_uuid::text || now()::text), 'hex');
  
  -- Set expiration time
  IF expires_hours IS NOT NULL THEN
    expires_at := NOW() + (expires_hours || ' hours')::INTERVAL;
  END IF;
  
  -- Create share record
  INSERT INTO portfolio_shares (portfolio_id, shared_by, share_token, permission_level, expires_at)
  VALUES (portfolio_uuid, shared_by_uuid, share_token, permission_level, expires_at);
  
  RETURN share_token;
END;
$$ LANGUAGE plpgsql;

-- Function to validate share token
CREATE OR REPLACE FUNCTION validate_portfolio_share(token TEXT)
RETURNS TABLE(
  portfolio_id UUID,
  permission_level TEXT,
  is_valid BOOLEAN,
  expires_at TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    ps.portfolio_id,
    ps.permission_level,
    ps.is_active AND (ps.expires_at IS NULL OR ps.expires_at > NOW()) AS is_valid,
    ps.expires_at
  FROM portfolio_shares ps
  WHERE ps.share_token = token;
END;
$$ LANGUAGE plpgsql;

-- Function to get collaboration statistics
CREATE OR REPLACE FUNCTION get_collaboration_stats(user_uuid UUID)
RETURNS TABLE(
  teams_count INTEGER,
  shared_projects_count INTEGER,
  comments_received INTEGER,
  comments_given INTEGER,
  total_activities INTEGER
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    (SELECT COUNT(*) FROM team_members WHERE user_id = user_uuid AND status = 'active'),
    (SELECT COUNT(*) FROM shared_projects sp 
     JOIN team_members tm ON sp.team_id = tm.team_id 
     WHERE tm.user_id = user_uuid AND tm.status = 'active'),
    (SELECT COUNT(*) FROM portfolio_comments pc 
     JOIN projects p ON pc.project_id = p.id 
     WHERE p.user_id = user_uuid),
    (SELECT COUNT(*) FROM portfolio_comments WHERE author_id = user_uuid),
    (SELECT COUNT(*) FROM collaboration_activities WHERE user_id = user_uuid);
END;
$$ LANGUAGE plpgsql;

-- Insert sample team workspace for testing
INSERT INTO team_workspaces (name, description, owner_id, is_public, invite_code)
VALUES 
(
  'Design Team',
  'Creative team for design projects and collaboration',
  (SELECT id FROM auth.users LIMIT 1),
  false,
  'DESIGN123'
),
(
  'Development Team',
  'Technical team for software development projects',
  (SELECT id FROM auth.users LIMIT 1),
  false,
  'DEV456'
);

-- Insert sample team members
INSERT INTO team_members (team_id, user_id, role, status, joined_at)
SELECT 
  tw.id,
  au.id,
  CASE WHEN tw.id = 1 THEN 'owner' ELSE 'editor' END,
  'active',
  NOW()
FROM team_workspaces tw
CROSS JOIN auth.users au
WHERE tw.id <= 2 AND au.id IS NOT NULL
LIMIT 4;
