-- Create portfolio templates table with sample data
-- Run this in your Supabase SQL Editor

-- Create portfolio templates table
CREATE TABLE IF NOT EXISTS portfolio_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('developer', 'designer', 'data_scientist', 'student', 'general')),
  preview_image TEXT,
  color_scheme JSONB DEFAULT '{"primary": "#8b5cf6", "secondary": "#6366f1", "accent": "#ec4899"}'::jsonb,
  layout_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  sections JSONB NOT NULL DEFAULT '["hero", "about", "skills", "projects", "contact"]'::jsonb,
  is_premium BOOLEAN DEFAULT FALSE,
  usage_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for category filtering
CREATE INDEX IF NOT EXISTS idx_portfolio_templates_category ON portfolio_templates(category);

-- Create index for premium filtering
CREATE INDEX IF NOT EXISTS idx_portfolio_templates_is_premium ON portfolio_templates(is_premium);

-- Insert default templates
INSERT INTO portfolio_templates (name, description, category, color_scheme, layout_config, sections) VALUES
(
  'Modern Developer',
  'Clean and professional template for software developers with focus on code projects',
  'developer',
  '{"primary": "#3b82f6", "secondary": "#06b6d4", "accent": "#10b981", "background": "#0f172a", "text": "#f8fafc"}'::jsonb,
  '{"hero_style": "centered", "project_cards": "minimal", "skills_display": "tags", "contact_form": true}'::jsonb,
  '["hero", "about", "skills", "projects", "contact"]'::jsonb
),
(
  'Creative Designer',
  'Bold and artistic template perfect for UI/UX designers and creative professionals',
  'designer',
  '{"primary": "#ec4899", "secondary": "#f97316", "accent": "#eab308", "background": "#18181b", "text": "#fafafa"}'::jsonb,
  '{"hero_style": "split", "project_cards": "masonry", "skills_display": "progress_bars", "contact_form": true}'::jsonb,
  '["hero", "about", "skills", "projects", "gallery", "contact"]'::jsonb
),
(
  'Data Scientist',
  'Analytical and data-focused template for data scientists and ML engineers',
  'data_scientist',
  '{"primary": "#22c55e", "secondary": "#3b82f6", "accent": "#8b5cf6", "background": "#0f172a", "text": "#f1f5f9"}'::jsonb,
  '{"hero_style": "centered", "project_cards": "detailed", "skills_display": "categories", "contact_form": false}'::jsonb,
  '["hero", "about", "skills", "experience", "projects", "publications", "contact"]'::jsonb
),
(
  'Student Portfolio',
  'Clean and simple template for students showcasing academic projects and learning journey',
  'student',
  '{"primary": "#6366f1", "secondary": "#8b5cf6", "accent": "#ec4899", "background": "#fafafa", "text": "#1f2937"}'::jsonb,
  '{"hero_style": "simple", "project_cards": "cards", "skills_display": "simple", "contact_form": true}'::jsonb,
  '["hero", "about", "education", "skills", "projects", "contact"]'::jsonb
),
(
  'Minimal Professional',
  'Elegant and minimal template suitable for any professional field',
  'general',
  '{"primary": "#000000", "secondary": "#6b7280", "accent": "#3b82f6", "background": "#ffffff", "text": "#111827"}'::jsonb,
  '{"hero_style": "minimal", "project_cards": "clean", "skills_display": "compact", "contact_form": true}'::jsonb,
  '["hero", "about", "skills", "projects", "contact"]'::jsonb
)
ON CONFLICT DO NOTHING;

-- Create user template selections table
CREATE TABLE IF NOT EXISTS user_template_selections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  template_id BIGINT NOT NULL REFERENCES portfolio_templates(id) ON DELETE CASCADE,
  customizations JSONB DEFAULT '{}'::jsonb,
  applied_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id)
);

-- Create index for user template lookups
CREATE INDEX IF NOT EXISTS idx_user_template_selections_user_id ON user_template_selections(user_id);

-- Function to increment template usage count
CREATE OR REPLACE FUNCTION increment_template_usage(template_id BIGINT)
RETURNS VOID AS $$
BEGIN
  UPDATE portfolio_templates 
  SET usage_count = usage_count + 1, updated_at = NOW()
  WHERE id = template_id;
END;
$$ LANGUAGE plpgsql;

-- Enable RLS for templates
ALTER TABLE portfolio_templates ENABLE ROW LEVEL SECURITY;

-- Everyone can view templates
CREATE POLICY "Anyone can view templates" ON portfolio_templates
  FOR SELECT USING (true);

-- Enable RLS for user template selections
ALTER TABLE user_template_selections ENABLE ROW LEVEL SECURITY;

-- Users can view their own template selections
CREATE POLICY "Users can view own template selections" ON user_template_selections
  FOR SELECT USING (auth.uid() = user_id);

-- Users can insert their own template selections
CREATE POLICY "Users can insert own template selections" ON user_template_selections
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users can update their own template selections
CREATE POLICY "Users can update own template selections" ON user_template_selections
  FOR UPDATE USING (auth.uid() = user_id);

-- Users can delete their own template selections
CREATE POLICY "Users can delete own template selections" ON user_template_selections
  FOR DELETE USING (auth.uid() = user_id);

RAISE NOTICE 'Portfolio templates table created and populated with sample data';
